### PR TITLE
Added cookie-parser middleware to the microservice

### PR DESCRIPTION
**Pull request by todesignandconquer**

### CODE REVIEW

**Comment by OronNadiv** [comment]
:+1:

**Comment by armw4** [comment]
:file_folder:

**Comment by apechimp** [comment]
I'm :-1: on this one: most microservices we have don't use cookies.

**Comment by OronNadiv** [comment]
But some do.  How do you suggest we solve it for those who do need it (ui-stagegate)?

**Comment by apechimp** [comment]
Install it as you would any other npm module and put it in the middleware array.

**Comment by OronNadiv** [comment]
Makes sense.  @todesignandconquer ^^^

**Comment by armw4** [comment]
👍

**Comment by DannyDouglass** [comment]
agreed with @apechimp :-1:

**Pull request merged**
