### PR TITLE
lanetix/issues#2108 Update jsonwebtoken

### PR DESCRIPTION
**Pull request by apechimp**

### CODE REVIEW

**Comment by apechimp** [comment]
CR @lanetix/engineers

**Comment by troygoode** [comment]
I don't think this is sufficient, is it @apechimp? My understanding from the article you posted this morning (https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) is that we should also be verifying that the client JWT's specified `alg` matches our server's expectations. Is that right?

**Comment by apechimp** [comment]
That's what auth0/node-jsonwebtoken#69 does (which is included in `4.2.2`). Its mechanism for doing so is checking to see whether or not you supplied a public key when verifying the token. If a public key is specified, it doesn't permit the use any of the hmac/sha algorithms. To be honest, this vulnerability probably won't affect us (at least in our current configuration) since we don't expose our services' public keys to the client (via the browser) and an attacker would need to sign a token with one of our public keys and set the `alg` to an hmac/sha algorithm to use this attack.

**Comment by troygoode** [comment]
okey doke :+1:

**Pull request merged**
