### PR TITLE
lanetix/issues#1851 Set lanetix-microservice to use eslint and nvm

### PR DESCRIPTION
**Pull request by OronNadiv**
@lanetix/engineers @apechimp CR Please.  Thanks

### CODE REVIEW

**Comment by scarney81** [comment]
:anchor:

**Comment by scarney81** [comment]
I was thinking (based on seeing this PR) - that we'll probably need to update the yeoman package to drop an nvmrc file in as well.

**Comment by OronNadiv** [comment]
@scarney81 I bumped the version of the package in order to be able to push a new version to yo.
About the nvmrc - why removing it?  It defines the default node version for the given microservice.

**Comment by apechimp** [comment]
@scarney81 is right, we need the .nvmrc in [the yeoman generator](https://github.com/lanetix/generator-lanetix-microservice). The .nvmrc needs to be in the root of the project, this will put it in `node_modules/lanetix-microservice`. Also, shouldn't the default be `iojs` :stuck_out_tongue_winking_eye:

**Comment by apechimp** [comment]
That being said, having the `.nvmrc` in this package is fine since it specifies the version of nvm for us to develop against.

**Comment by OronNadiv** [comment]
Yeah, I just realized we have two repos - node-lanetix-microservice and generator-ms.  How are they related?

**Comment by apechimp** [comment]
this is an npm module which is a framework for building microservices with, the generator is basically a template for a microservice.

**Comment by OronNadiv** [comment]
Got it.  I'll have a separate PR for the generator template.

**Comment by scarney81** [comment]
Sorry - realized that I made it look like I said to remove the .nvmrc. I meant to say "place a .nvmrc" file using the yeoman generator. My beezie

**Pull request merged**
